# Generated by Django 3.1.2 on 2020-10-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201022_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='email',
            field=models.EmailField(max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='mobile_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='types',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
