# Generated by Django 3.1.2 on 2020-10-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0003_auto_20201015_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(null=True, upload_to='blog_pics/'),
        ),
    ]
